package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"log"
	"math/rand"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
)

type NetEvent struct {
	AgentID   string                 `json:"agent_id"`
	EventType string                 `json:"event_type"`
	Timestamp time.Time              `json:"timestamp"`
	SrcIP     string                 `json:"src_ip,omitempty"`
	DstIP     string                 `json:"dst_ip,omitempty"`
	SrcPort   int                    `json:"src_port,omitempty"`
	DstPort   int                    `json:"dst_port,omitempty"`
	Proto     string                 `json:"proto,omitempty"`
	Bytes     int                    `json:"bytes,omitempty"`
	Extra     map[string]interface{} `json:"extra"`
}

func main() {
	agentID := getEnv("NETWATCH_AGENT_ID", "agent-unknown")
	apiURL := getEnv("NETWATCH_API_URL", "http://localhost:8000")
	mode := getEnv("NETWATCH_AGENT_MODE", "mock") // "mock" ou "proc"

	log.Printf("[AGENT] Starting with ID=%s, backend=%s, mode=%s", agentID, apiURL, mode)

	rand.Seed(time.Now().UnixNano())

	// Alvos simulados para o modo "mock"
	dstIPs := []string{
		"10.0.0.20",
		"10.0.0.21",
		"10.0.0.22",
	}

	dstPorts := []int{
		22,   // SSH
		80,   // HTTP
		443,  // HTTPS
		8080, // alt HTTP
		3306, // MySQL
		5432, // Postgres
	}

	ticker := time.NewTicker(10 * time.Second)
	defer ticker.Stop()

	for range ticker.C {
		var events []NetEvent
		var err error

		switch mode {
		case "proc":
			events, err = captureFromProc(agentID)
			if err != nil {
				log.Printf("[AGENT] captureFromProc error: %v", err)
				continue
			}
			if len(events) == 0 {
				log.Printf("[AGENT] no TCP connections found in /proc/net/tcp")
				continue
			}
		default: // "mock"
			events = []NetEvent{generateMockEvent(agentID, dstIPs, dstPorts)}
		}

		payload, err := json.Marshal(events)
		if err != nil {
			log.Printf("[AGENT] Failed to serialize event batch: %v", err)
			continue
		}

		resp, err := http.Post(apiURL+"/ingest/events", "application/json", bytes.NewReader(payload))
		if err != nil {
			log.Printf("[AGENT] Failed to send event batch: %v", err)
			continue
		}
		_ = resp.Body.Close()

		log.Printf("[AGENT] Sent %d event(s), status=%d", len(events), resp.StatusCode)
	}
}

// ---- Modo MOCK ----------------------------------------------------

func generateMockEvent(agentID string, dstIPs []string, dstPorts []int) NetEvent {
	dstIP := dstIPs[rand.Intn(len(dstIPs))]
	dstPort := dstPorts[rand.Intn(len(dstPorts))]

	return NetEvent{
		AgentID:   agentID,
		EventType: "flow",
		Timestamp: time.Now().UTC(),
		SrcIP:     "10.0.0.10",
		DstIP:     dstIP,
		SrcPort:   54321,
		DstPort:   dstPort,
		Proto:     "tcp",
		Bytes:     1024,
		Extra: map[string]interface{}{
			"flow_id": uuid.New().String(),
			"note":    "mock flow event generated by the agent",
		},
	}
}

// ---- Modo PROC (/proc/net/tcp) ------------------------------------

func captureFromProc(agentID string) ([]NetEvent, error) {
	f, err := os.Open("/proc/net/tcp")
	if err != nil {
		return nil, fmt.Errorf("failed to open /proc/net/tcp: %w", err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	events := make([]NetEvent, 0)

	firstLine := true
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		// pula cabeçalho
		if firstLine {
			firstLine = false
			continue
		}

		fields := strings.Fields(line)
		if len(fields) < 4 {
			continue
		}

		localAddr := fields[1]
		remAddr := fields[2]
		state := fields[3]

		// "01" = ESTABLISHED
		if state != "01" {
			continue
		}

		srcIP, srcPort, err := parseHexIPPort(localAddr)
		if err != nil {
			continue
		}
		dstIP, dstPort, err := parseHexIPPort(remAddr)
		if err != nil {
			continue
		}

		ev := NetEvent{
			AgentID:   agentID,
			EventType: "flow",
			Timestamp: time.Now().UTC(),
			SrcIP:     srcIP,
			DstIP:     dstIP,
			SrcPort:   srcPort,
			DstPort:   dstPort,
			Proto:     "tcp",
			Bytes:     0,
			Extra: map[string]interface{}{
				"flow_id": uuid.New().String(),
				"note":    "tcp entry from /proc/net/tcp",
			},
		}
		events = append(events, ev)
	}

	if err := scanner.Err(); err != nil {
		return events, fmt.Errorf("scanner error: %w", err)
	}

	return events, nil
}

// parseHexIPPort converte o formato "0100007F:0016" em "127.0.0.1", 22
func parseHexIPPort(s string) (string, int, error) {
	parts := strings.Split(s, ":")
	if len(parts) != 2 {
		return "", 0, fmt.Errorf("invalid addr: %s", s)
	}

	ipHex := parts[0]
	portHex := parts[1]

	if len(ipHex) != 8 {
		return "", 0, fmt.Errorf("invalid ip hex: %s", ipHex)
	}

	ipBytes := make([]byte, 4)
	for i := 0; i < 4; i++ {
		b, err := strconv.ParseUint(ipHex[2*i:2*i+2], 16, 8)
		if err != nil {
			return "", 0, fmt.Errorf("invalid ip byte in %s: %w", ipHex, err)
		}
		// /proc/net/tcp traz IP em little endian
		ipBytes[3-i] = byte(b)
	}

	ip := fmt.Sprintf("%d.%d.%d.%d", ipBytes[0], ipBytes[1], ipBytes[2], ipBytes[3])

	port64, err := strconv.ParseUint(portHex, 16, 16)
	if err != nil {
		return "", 0, fmt.Errorf("invalid port in %s: %w", s, err)
	}

	return ip, int(port64), nil
}

// ---- Util ---------------------------------------------------------

func getEnv(key, def string) string {
	if v, ok := os.LookupEnv(key); ok {
		return v
	}
	return def
}
